name: Hourly Build and Deploy

on:
  schedule:
    - cron: "7 * * * *"   # every hour at :07 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: [self-hosted]   # or [self-hosted, fm25] if you added that label
    env:
      LEAGUE_ID: "508419792"
      SEASON: "2025"
      # Map your existing secrets to the names the script accepts
      SWID: ${{ secrets.ESPN_SWID }}
      ESPN_S2: ${{ secrets.ESPN_S2 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "requests>=2.31,<3"

      - name: Fetch ESPN league JSON
        run: |
          python pipeline/fetch_espn_all.py

      - name: Commit & push JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          git add docs/data || true
          git commit -m "robot: refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
