name: Run Weekly Matchup Analysis

on:
  workflow_dispatch: # Allows you to run this manually

jobs:
  run-matchup-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Matchup Analyzer Script
        run: python analysis/matchup_analyzer.py
      
      - name: Commit Matchup Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🎯 Chore: Update weekly matchup analysis"
          file_pattern: "docs/data/analysis/matchup_report.json"
