name: Hourly Build and Deploy

on:
  schedule:
    - cron: '15 * * * *'   # hourly at :15
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      LEAGUE_ID: '508419792'
      SEASON: '2025'
      # The runner or repo secrets must provide SWID and ESPN_S2
      # We’ll read from env at runtime inside the Python scripts.

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch league (teams + rosters)
        env:
          SWID: ${{ secrets.SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
        run: |
          python pipeline/fetch_league.py

      - name: Fetch players (with public fallback)
        env:
          SWID: ${{ secrets.SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
        run: |
          python pipeline/fetch_players.py

      - name: Commit data (if changed)
        run: |
          git config user.name "gh-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/data/*.json || true
          if ! git diff --cached --quiet; then
            git commit -m "Update data ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "No data changes"
          fi
