name: Hourly Build

on:
  schedule:
    - cron: "0 * * * *"   # top of every hour (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: fantasymanager25-hourly
  cancel-in-progress: true

env:
  SEASON: "2025"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Fetch ESPN (public)
        env:
          LEAGUE_ID: "508419792"  # set your ID here or use a repo secret
          SEASON: ${{ env.SEASON }}
        run: python pipeline/fetch_espn_public.py

      - name: Commit & push JSON
        run: |
          git config user.email "robot@users.noreply.github.com"
          git config user.name "robot"
          git add docs/data/espn_*.json docs/data/status.json
          git commit -m "robot: espn refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
