name: Build Player Points (League-Scoring)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 9 * * 4"   # Thu 09:15 UTC (adjust if you want)

jobs:
  build-points:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get NFL data
        run: |
          python pipeline/get_nfl_data.py

      - name: Build league-scored points
        run: |
          python analysis/player_points.py

      - name: Commit artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data/analysis/*.json
          git commit -m "Update league-scored points" || echo "No changes"
          git push
