name: hourly

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 * * * *"   # hourly at :17

permissions:
  contents: write

concurrency:
  group: hourly-${{ github.ref }}
  cancel-in-progress: false

jobs:
  hourly:
    runs-on: self-hosted
    env:
      HOME: /home/ghrunner
      PLAYWRIGHT_BROWSERS_PATH: /home/ghrunner/.cache/ms-playwright
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade playwright requests cloudscraper

      # IMPORTANT: install the Playwright-managed Chromium in this HOME
      - name: Install Playwright Chromium
        run: |
          python -m playwright install chromium
          python -m playwright --version

      # Get cookies headlessly and export SWID/ESPN_S2 to job env
      - name: Get ESPN cookies via Playwright
        env:
          ESPN_USER: ${{ secrets.ESPN_USER }}
          ESPN_PASS: ${{ secrets.ESPN_PASS }}
        run: |
          python pipeline/get_espn_cookies.py --league 508419792 --write-github-env "$GITHUB_ENV"

      - name: Fetch league
        env:
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_league.py

      - name: Fetch rosters
        env:
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_rosters.py

      - name: Fetch players
        run: python pipeline/fetch_players.py

      - name: Commit data
        run: |
          git config user.name "robot"
          git config user.email "robot@users.noreply.github.com"
          git add docs/data
          git commit -m "robot: refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "nothing to commit"
          git push
