name: Hourly Build

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # allows manual run

permissions:
  contents: write  # <-- Needed so the bot can commit to repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch ESPN (public)
        run: |
          python fetch_espn.py

      - name: Commit & push JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add docs/data/*.json
          git commit -m "Update ESPN JSON data" || echo "No changes to commit"
          git push
