name: Process and Deploy Fantasy Data

on:
  # This workflow now runs ONLY when you push changes to the master data file
  push:
    branches:
      - main
    paths:
      - 'docs/data/fantasy_league_data.json'
  
  # We'll also keep the manual trigger
  workflow_dispatch:

jobs:
  process-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Process Master Data File
        run: python pipeline/process_data.py

      - name: Commit Processed Files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Chore: Process and update website data"
          # Add all new and changed json files
          file_pattern: "docs/data/*.json"
