name: File Path Diagnostic

on:
  workflow_dispatch:

jobs:
  diagnose-file-paths:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Show the entire file structure
        run: ls -R
