    - name: Ensure pip deps (once)
      run: |
        python -m pip install --upgrade pip
        pip install playwright
    - name: Get ESPN cookies with Playwright
      env:
        ESPN_USER: ${{ secrets.ESPN_USER }}
        ESPN_PASS: ${{ secrets.ESPN_PASS }}
        PLAYWRIGHT_BROWSERS_PATH: ${{ vars.PLAYWRIGHT_BROWSERS_PATH }}
        PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: ${{ vars.PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS }}
        ARTIFACTS_DIR: artifacts
      run: |
        mkdir -p artifacts
        python pipeline/get_espn_cookies.py --league "${{ vars.LEAGUE_ID }}" --write-github-env "$GITHUB_ENV"
    - name: Upload login screenshots (if any)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-login
        path: artifacts
