name: Hourly Build and Deploy

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "requests>=2.31,<3"

      - name: Ensure docs/data exists
        run: |
          mkdir -p docs/data
          echo '{}' > docs/data/status.json

      - name: Fetch ESPN league core (standings/rosters/etc)
        env:
          LEAGUE_ID: "508419792"
          SEASON: "2025"
          ESPN_SWID: ${{ secrets.ESPN_SWID }}
          ESPN_S2:   ${{ secrets.ESPN_S2 }}
        run: |
          python pipeline/fetch_espn_all.py

      - name: Fetch ESPN players (public catalog + projections)
        env:
          SEASON: "2025"
          ESPN_SWID: ${{ secrets.ESPN_SWID }}
          ESPN_S2:   ${{ secrets.ESPN_S2 }}
        run: |
          python pipeline/fetch_players.py

      - name: Build team_rosters.json from ESPN files
        run: |
          python pipeline/build_team_rosters.py

      - name: Commit & push JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data
          git commit -m "robot: refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
