name: Hourly Data Build

on:
  workflow_dispatch:
  schedule:
    - cron: '9 * * * *'
  push:
    paths:
      - 'pipeline/**'
      - 'docs/**'
      - '.github/workflows/hourly.yml'

permissions:
  contents: write

concurrency:
  group: hourly-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade playwright cloudscraper requests pydantic

      - name: Ensure Chromium (no sudo)
        run: |
          python -m playwright install chromium || true

      - name: Set required environment variables
        run: |
          echo "LEAGUE_ID=${{ vars.LEAGUE_ID || '508419792' }}" >> $GITHUB_ENV
          echo "PLAYWRIGHT_BROWSERS_PATH=${{ vars.PLAYWRIGHT_BROWSERS_PATH || '/home/ghrunner/.cache/ms-playwright' }}" >> $GITHUB_ENV
          echo "PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=${{ vars.PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS || '1' }}" >> $GITHUB_ENV

      - name: Prefer cookie secrets if present
        if: ${{ secrets.ESPN_SWID != '' && secrets.ESPN_S2 != '' }}
        run: |
          echo "SWID=${{ secrets.ESPN_SWID }}" >> $GITHUB_ENV
          echo "ESPN_S2=${{ secrets.ESPN_S2 }}" >> $GITHUB_ENV
          echo "ESPN_USER=skip" >> $GITHUB_ENV
          echo "ESPN_PASS=skip" >> $GITHUB_ENV

      - name: Login to ESPN to get cookies (Playwright)
        if: ${{ secrets.ESPN_SWID == '' || secrets.ESPN_S2 == '' }}
        env:
          ESPN_USER: ${{ secrets.ESPN_USER }}
          ESPN_PASS: ${{ secrets.ESPN_PASS }}
        run: |
          mkdir -p artifacts
          python pipeline/get_espn_cookies.py --league-id "${{ env.LEAGUE_ID }}" >> $GITHUB_ENV

      - name: Verify cookies
        run: |
          : "${{ env.ESPN_S2:?ESPN_S2 missing}}"
          : "${{ env.SWID:?SWID missing}}"
          echo "Cookies present."

      - name: Fetch players
        env:
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
        run: python pipeline/fetch_players.py

      - name: Fetch league
        env:
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
        run: python pipeline/fetch_league.py

      - name: Fetch rosters
        env:
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
        run: python pipeline/fetch_rosters.py

      - name: Commit JSON updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "robot: refresh ${{ env.LEAGUE_ID }}"
          file_pattern: docs/data/*.json

      - name: Upload login screenshots (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-login
          path: artifacts
          if-no-files-found: ignore
