name: Hourly Build

on:
  schedule:
    - cron: "0 * * * *"   # hourly (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: fantasymanager25-hourly
  cancel-in-progress: true

env:
  SEASON: "2025"    # adjust if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Run ESPN sync
        env:
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          ESPN_SWID: ${{ secrets.ESPN_SWID }}
          ESPN_S2:   ${{ secrets.ESPN_S2 }}
        run: |
          python pipeline/run_all.py

      - name: Commit and push JSON outputs
        run: |
          git config user.email "robot@users.noreply.github.com"
          git config user.name "robot"
          git add docs/data/status.json docs/data/latest.json
          git commit -m "robot: update data $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes to commit"
          git push
