name: Run VORP Draft Analysis

on:
  workflow_dispatch: # Allows you to run this manually

jobs:
  run-vorp-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run VORP Calculator Script
        run: python analysis/vorp_calculator.py
      
      - name: Commit VORP Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📈 Chore: Update VORP analysis data"
          file_pattern: "docs/data/analysis/vorp_analysis.json"
