name: Run Waiver Wire Analysis

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  run-waiver-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        # This step checks out the repository code, including the big data CSV
        uses: actions/checkout@v4
        with:
          # Fetches the entire git history so we can read the data file
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Waiver Wire Script
        run: python analysis/waiver_wire.py
