name: Run Draft Tier Analysis

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  run-draft-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Draft Tier Generator Script
        run: python analysis/draft_tier_generator.py
