name: Hourly Data Build

on:
  workflow_dispatch:
  schedule:
    - cron: '9 * * * *'
  push:
    paths:
      - 'pipeline/**'
      - 'docs/**'
      - '.github/workflows/hourly.yml'

permissions:
  contents: write

concurrency:
  group: hourly-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade playwright requests pydantic

      - name: Ensure Chromium
        run: |
          python -m playwright install chromium || true

      - name: Fetch and process all data
        env:
          LEAGUE_ID: ${{ vars.LEAGUE_ID }}
          ESPN_USER: ${{ secrets.ESPN_USER }}
          ESPN_PASS: ${{ secrets.ESPN_PASS }}
          SWID: ${{ secrets.ESPN_SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
        run: python pipeline/fetch_all_data.py

      - name: Commit JSON updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "robot: refresh data"
          file_pattern: docs/data/*.json
