name: Hourly Build and Deploy

on:
  schedule:
    - cron: "8 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    env:
      PYTHONUNBUFFERED: "1"
      LEAGUE_ID: "508419792"
      SEASON: "2025"
      PLAYWRIGHT_BROWSERS_PATH: "$HOME/.cache/ms-playwright"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Sanity check Playwright
        run: python -m playwright --version

      # Get fresh cookies each run (no manual SWID/ESPN_S2 upkeep)
      - name: Get ESPN cookies via Playwright
        env:
          ESPN_USER: ${{ secrets.ESPN_USER }}
          ESPN_PASS: ${{ secrets.ESPN_PASS }}
          GITHUB_ENV: ${{ env.GITHUB_ENV }}
        run: |
          if [ -z "${ESPN_USER}" ] || [ -z "${ESPN_PASS}" ]; then
            echo "ESPN_USER/ESPN_PASS secrets are required for login."
            exit 1
          fi
          python pipeline/get_espn_cookies.py --league "${{ env.LEAGUE_ID }}" --write-github-env "$GITHUB_ENV"
          echo "SWID/ESPN_S2 set in job env."

      - name: Assert cookies exist
        run: |
          [ -z "${SWID:-}" ] && echo "SWID missing" && exit 1 || echo "SWID OK"
          [ -z "${ESPN_S2:-}" ] && echo "ESPN_S2 missing" && exit 1 || echo "ESPN_S2 OK"

      - name: Fetch League (teams/standings/settings)
        env:
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
          SEASON: ${{ env.SEASON }}
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_league.py

      - name: Fetch Rosters
        env:
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
          SEASON: ${{ env.SEASON }}
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_rosters.py

      - name: Fetch Players
        env:
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
          SEASON: ${{ env.SEASON }}
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_players.py

      - name: Commit and push data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/data/*.json || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "robot: refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
