name: Hourly Build and Deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: self-hosted

    # only league/season here; DO NOT set SWID/ESPN_S2 so we inherit from runner env
    env:
      LEAGUE_ID: "508419792"
      SEASON: "2025"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Preflight – verify runner env contains cookies
        shell: bash
        run: |
          MISSING=0
          if [ -z "${SWID}" ];   then echo "::error::SWID env is not set (runner)"; MISSING=1; fi
          if [ -z "${ESPN_S2}" ]; then echo "::error::ESPN_S2 env is not set (runner)"; MISSING=1; fi
          if [ "$MISSING" -ne 0 ]; then
            echo "You set SWID/ESPN_S2 in /etc/environment — make sure the runner service is restarted and sees them."
            echo "Alternative: add repo Secrets SWID and ESPN_S2, then we can map them explicitly."
            exit 1
          fi
          echo "Runner environment has SWID/ESPN_S2 (values hidden)."

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch ESPN (authenticated)
        run: |
          python pipeline/fetch_espn_all.py \
            --league "$LEAGUE_ID" \
            --season "$SEASON" \
            --out docs/data

      - name: Build team_rosters.json
        run: |
          python pipeline/build_team_rosters.py

      - name: Fetch players summary
        run: |
          python pipeline/fetch_players.py

      - name: Commit and push JSON
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "actions@github.com"
          git add docs/data/*.json || true
          if git diff --cached --quiet; then
            echo "No JSON changes to commit."
            exit 0
          fi
          git commit -m "robot: refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push origin HEAD:main
