name: Fetch NFL Data

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '0 10 * * *' # Runs daily at 10:00 UTC

jobs:
  fetch-nfl-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Data Collection Script
        run: python pipeline/get_nfl_data.py
      
      - name: Commit New Data File
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🏈 Chore: Update historical NFL and weather data"
          file_pattern: data/analysis/*.csv
