name: Hourly Build and Deploy

on:
  schedule:
    - cron: "8 * * * *"   # minute 8 every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # your VPS runner
    env:
      PYTHONUNBUFFERED: "1"
      LEAGUE_ID: "508419792"
      SEASON: "2025"
      # Reuse the runner's installed browsers
      PLAYWRIGHT_BROWSERS_PATH: "$HOME/.cache/ms-playwright"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project deps
        run: pip install -r requirements.txt

      - name: Sanity check Playwright exists on runner (no sudo, no install)
        run: |
          python -m playwright --version || (echo "Playwright missing on runner. SSH and run the setup we did." && exit 1)

      # ---- PLAYWRIGHT LOGIN: get SWID + ESPN_S2 from real browser session ----
      - name: Get ESPN cookies via Playwright
        env:
          ESPN_USER: ${{ secrets.ESPN_USER }}
          ESPN_PASS: ${{ secrets.ESPN_PASS }}
          GITHUB_ENV: ${{ env.GITHUB_ENV }}
        run: |
          python pipeline/get_espn_cookies.py --league "${{ env.LEAGUE_ID }}" --write-github-env "$GITHUB_ENV"
          echo "Cookies harvested and exported to env."

      # ---- FETCHERS (now see SWID/ESPN_S2 from previous step) ----
      - name: Fetch League
        env:
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
          SEASON: ${{ env.SEASON }}
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_league.py

      - name: Fetch Rosters
        env:
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
          SEASON: ${{ env.SEASON }}
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_rosters.py

      - name: Fetch Players
        env:
          LEAGUE_ID: ${{ env.LEAGUE_ID }}
          SEASON: ${{ env.SEASON }}
          SWID: ${{ env.SWID }}
          ESPN_S2: ${{ env.ESPN_S2 }}
        run: python pipeline/fetch_players.py

      - name: Commit and push data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/data/*.json || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "robot: refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
