name: Hourly Data Build

on:
  workflow_dispatch:
  schedule:
    - cron: '9 * * * *'
  push:
    paths:
      - 'pipeline/**'
      - 'docs/**'
      - '.github/workflows/hourly.yml'

permissions:
  contents: write

concurrency:
  group: hourly-build
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 25
    env:
      LEAGUE_ID: ${{ vars.LEAGUE_ID || '508419792' }}
      PLAYWRIGHT_BROWSERS_PATH: ${{ vars.PLAYWRIGHT_BROWSERS_PATH || '/home/ghrunner/.cache/ms-playwright' }}
      PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS: ${{ vars.PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS || '1' }}
      ESPN_SWID: ''
      ESPN_S2: ''
      SWID: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install --upgrade playwright cloudscraper requests pydantic

      - name: Ensure Chromium (no sudo)
        run: |
          python -m playwright install chromium || true

      - name: Set cookies from secrets if present
        if: ${{ secrets.ESPN_SWID != '' && secrets.ESPN_S2 != '' }}
        run: |
          echo "ESPN_SWID=${{ secrets.ESPN_SWID }}" >> "$GITHUB_ENV"
          echo "ESPN_S2=${{ secrets.ESPN_S2 }}" >> "$GITHUB_ENV"
          echo "SWID=${{ secrets.ESPN_SWID }}" >> "$GITHUB_ENV"

      - name: Login to ESPN to get cookies (Playwright)
        if: ${{ env.ESPN_SWID == '' || env.ESPN_S2 == '' }}
        env:
          ESPN_USER: ${{ secrets.ESPN_USER }}
          ESPN_PASS: ${{ secrets.ESPN_PASS }}
        run: |
          mkdir -p artifacts
          python pipeline/get_espn_cookies.py --league-id "${LEAGUE_ID}" >> "$GITHUB_ENV"

      - name: Verify cookies
        run: |
          : "${ESPN_S2:?ESPN_S2 missing}"
          : "${SWID:?SWID missing}"
          echo "Cookies present."

      - name: Fetch players
        run: python pipeline/fetch_players.py

      - name: Fetch league
        run: python pipeline/fetch_league.py

      - name: Fetch rosters
        run: python pipeline/fetch_rosters.py

      - name: Commit JSON updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "robot: refresh ${{ env.LEAGUE_ID }}"
          file_pattern: docs/data/*.json

      - name: Upload login screenshots (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-login
          path: artifacts
          if-no-files-found: ignore
