name: Hourly Build and Deploy

on:
  schedule:
    - cron: "7 * * * *"    # hourly at minute 7
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch all ESPN data
        env:
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          SWID: ${{ secrets.SWID }}
          LEAGUE_ID: "508419792"
          SEASON: "2025"
        run: |
          python pipeline/fetch_espn_all.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git add docs/data/*.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "robot: espn refresh $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
