name: Run Consistency Analysis

on:
  workflow_dispatch: # Allows you to run this manually

jobs:
  run-consistency-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Consistency Analyzer Script
        run: python analysis/consistency_analyzer.py
      
      - name: Commit Consistency Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🎯 Chore: Update consistency analysis data"
          file_pattern: "docs/data/analysis/consistency_report.json"
